config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'pets', to: 'pets#index'
  get 'pets/new', to: 'pets#new'
  get 'pets/:id', to: 'pets#show', as: :pet
  post 'pets', to: 'pets#create'
  get 'pets/:id/edit', to: 'pets#edit'
  patch 'pets/:id', to: 'pets#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = %w(dog cat snake turtle eagle).freeze

  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    (Date.today - date_found).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    pet = Pet.new(pet_params_create)
    pet.save

    redirect_to pet_path(pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    pet = Pet.find(params[:id])
    pet.update(pet_params_create)

    redirect_to pet_path(pet)
  end

  private

  def pet_params_create
    params.require(:pet).permit(:name, :address, :species, :date_found)
  end

  # def pet_params_update
  #   params.require(:pet).permit(:name, :address, :date_found)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="row">
  <div class="col-6 offset-3">
    <%= simple_form_for(@pet) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :species, collection: Pet::SPECIES %>
      <%= f.input :date_found %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/index.html.erb
<h1>Lost & Found Pets</h1>

<p><%= link_to "Report a new lost pet", pets_new_path %></p>

<ul>
  <% @pets.each do |pet| %>
    <li><%= link_to pet.name, pet_path(pet) %> - found <%= pet.found_days_ago %> days ago</li>
  <% end %>
</ul>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1600x900/?<%= @pet.species %>
);">
  <div class="container">
    <h1><%= @pet.name %></h1>
    <a class="btn btn-primary" href="#">I'm the owner</a>
  </div>
</div>

<ul>
  <li>Species: <%= @pet.species.capitalize %></li>
  <li>Address: <%= @pet.address %></li>
  <li>Found <%= @pet.found_days_ago %> days ago</li>
</ul>